env: "local" # local, dev, prod
storage_path: "D:/go_path/src/url-shortener/storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: admin
  password: 222
clients:
  sso:
    address: "localhost:44544"
    timeout: 10s
    RetriesCount: 10
    Insecure: false